In [36]:
import numpy as np

Q1 What is numpy?
*   Numpy stands for numerical python. It is a Python Library.
*   It is used for computation and processing array elements. 

Q2 Why should we use numpy?
*   It provides a powerful and efficient way to work with arrays of data.
*   We can perform various mathematical operations in numpy arrays. 

Q3 Why numpy arrays are better than list?
*   It takes less memory usage
*   Less execution time


In [38]:
#Q4 What are the ways of creating 1d 2d and 3d arr
arr1d = np.array([1,2,3])
arr_1d = np.array([1,2,3], ndmin=1) 
print(arr1d)
print(arr_1d)

[1 2 3]
[1 2 3]


In [39]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr_2d = np.array([1,2,3,4,5,6], ndmin=2)
print(arr2d)
print(arr_2d)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [40]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr_3d = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)
print(arr3d)
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3 4 5 6 7 8 9]]]


In [41]:
#Q5 How to find out data type of elements present in the numpy arrays?
arr = np.array([1,2,3])
arr1 = np.array([1.1,1.2,1.3])
print(arr.dtype)
print(arr1.dtype)

int64
float64


In [42]:
#Q6 Give on example for zeros, ones functions (take 3,3 matrix)
arr_zeros = np.zeros((3,3))
arr_ones = np.ones((3,3))
print(arr_zeros)
print(arr_ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
# a = np.array([1,2,3,4,5,6,7,8,9])
#Q7 Retrive all elements from above array using for loop
a = np.array([1,2,3,4,5,6,7,8,9])
for i in a:
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 

In [44]:
#Q8 By using random.randint function create (5,5)matrix and find the maximun and minimum number present in the array

b = np.random.randint(1,30,(5,5))
print(b)
print("Maximum element in array: ",b.max())
print("Minimum element in array: ",b.min())

[[26 29 25 18 11]
 [20  2 24 19  8]
 [11  1 10  8 17]
 [14 18 13 24 22]
 [ 9 10 28  1 19]]
Maximum element in array:  29
Minimum element in array:  1


In [45]:
#Q9 By using random.randint function create (3,3)matrix and do the reshape for all the possibilities?
c = np.random.randint(1,15,(3,3))
print(c)
# only two possiblities [9,1], [1,9]
print(np.reshape(c,[1,9]))
print(np.reshape(c,[9,1]))

[[ 6 14 13]
 [ 7  9 14]
 [11  9  3]]
[[ 6 14 13  7  9 14 11  9  3]]
[[ 6]
 [14]
 [13]
 [ 7]
 [ 9]
 [14]
 [11]
 [ 9]
 [ 3]]


In [46]:
#Q10 Create (5,5)matrix and retrieve the elements present in 3rd and 5th row by using row slicing
d = np.random.randint(1,30,(5,5))
print(d)
print(d[[3],:])
# print(d[3:5:2, : ])

[[ 5  9 22  5 16]
 [20 24 19 18 19]
 [ 6 21 25 22  9]
 [23 26 14 25 21]
 [ 9 21 13 28 14]]
[[23 26 14 25 21]]


In [47]:
#Q11 Explain about insert function by giving one example
# Insert function inserts values in the given array along the given axis and before the given index
# numpy.insert(arr, index, values, axis), 

e = np.array([[1,2],[3,4],[5,6]])
print(np.insert(e, 1, [2,3], axis=0))
print(np.insert(e, 1, [7,8,9], axis=1))

[[1 2]
 [2 3]
 [3 4]
 [5 6]]
[[1 7 2]
 [3 8 4]
 [5 9 6]]


In [48]:
#Q12 Take any example of the numpy array and transpose it
f = np.random.randint(1,15,(3,3))
print("Original array: ")
print(f)
print("Transpose array: ")
print(f.T)  

Original array: 
[[14  3  3]
 [11  2  3]
 [14  5  1]]
Transpose array: 
[[14 11 14]
 [ 3  2  5]
 [ 3  3  1]]
